export const QUOTES = {
  motivate: [
    { m: "You are not behind.", s: "You are exactly where you need to be." },
    { m: "The version of you that gave up doesn't exist.", s: "Keep going." },
    { m: "Small steps still move you forward.", s: "Don't discount what you're doing." },
    { m: "You've survived 100% of your bad days.", s: "That's your track record." },
    { m: "Rest is not failure.", s: "It's strategy." },
    { m: "The work you're doing right now matters.", s: "Even when it doesn't feel like it." },
    { m: "Nobody who kept going ever regretted it.", s: "Not one person." },
    { m: "You've done hard things before.", s: "This is just the next one." },
    { m: "The fact that you're still trying says everything.", s: "Don't underestimate that." },
    { m: "One more day.", s: "That's all you have to do." },
    { m: "You don't have to feel motivated to move.", s: "Movement creates motivation. Not the other way around." },
    { m: "The version of you that makes it through this exists.", s: "You just haven't met her yet." },
  ],
  comfort: [
    { m: "You are allowed to fall apart.", s: "That's not weakness. That's being human." },
    { m: "You don't have to hold it together today.", s: "Let yourself feel it." },
    { m: "Being tired is valid.", s: "You've been carrying a lot." },
    { m: "You are enough as you are right now.", s: "Not when you fix things. Now." },
    { m: "It's okay to need people.", s: "That's not a flaw. That's connection." },
    { m: "You're allowed to have a bad day.", s: "It doesn't cancel out all the good ones." },
    { m: "You don't have to earn rest.", s: "You just have to take it." },
    { m: "Some days surviving is the whole achievement.", s: "And that counts." },
    { m: "The way you talk to yourself matters.", s: "You're listening." },
    { m: "You are not too much.", s: "You've just been around people who couldn't hold you." },
    { m: "Crying isn't breaking down.", s: "It's releasing what doesn't fit anymore." },
    { m: "You are allowed to outgrow things that once felt like home.", s: "That's not betrayal. That's growth." },
  ],
  predict: [
    { m: "Something you've been waiting for is closer than it looks.", s: "Trust the timing." },
    { m: "The plot twist is coming.", s: "And you'll love where it leads." },
    { m: "A door is about to open.", s: "Stop staring at the closed ones." },
    { m: "You'll laugh about this in two years.", s: "The story isn't over yet." },
    { m: "The best version of this situation is still possible.", s: "Keep showing up." },
    { m: "The universe is rearranging itself in your favour.", s: "Stay open to it." },
    { m: "The thing you're afraid to want is exactly what's coming.", s: "Let yourself want it." },
    { m: "This chapter feels long because it's important.", s: "Something is being built in you." },
    { m: "The right people haven't left yet.", s: "Some of them haven't arrived." },
    { m: "You're closer to the other side than you think.", s: "Keep walking." },
    { m: "What's meant for you won't require you to shrink.", s: "Remember that." },
    { m: "Six months from now, this will look different.", s: "Hold on for the view." },
  ],
  honest: [
    { m: "You already know what you need to do.", s: "You're just waiting to feel ready. You won't." },
    { m: "The thing you're procrastinating on?", s: "It'll take less time than the guilt." },
    { m: "Stop explaining yourself to people who don't ask.", s: "Your energy is finite." },
    { m: "You're not stuck.", s: "You're comfortable. Those are different." },
    { m: "The you from a year ago would be proud.", s: "Be honest — you've grown." },
    { m: "The only thing standing between you and it is you.", s: "Step aside." },
    { m: "You've been waiting for permission.", s: "This is it. Go." },
    { m: "The conversation you keep avoiding is the one you need to have.", s: "You know which one." },
    { m: "You're not protecting them by staying small.", s: "You're just staying small." },
    { m: "The life you want requires a version of you willing to be uncomfortable.", s: "Are you?" },
    { m: "You keep saying 'eventually'.", s: "Eventually is now or it's never." },
    { m: "Stop waiting to feel like yourself again.", s: "You have to build that person. She won't just appear." },
  ],
};

export const MOOD_LABELS = {
  motivate: "MOTIVATE ME",
  comfort: "COMFORT ME",
  predict: "PREDICT ME",
  honest: "BE HONEST",
};

export const MOODS = [
  { id: "motivate", emoji: "🚀", label: "Motivate Me" },
  { id: "comfort",  emoji: "☕", label: "Comfort Me" },
  { id: "predict",  emoji: "🔮", label: "Predict Me" },
  { id: "honest",   emoji: "🕶️", label: "Be Honest" },
];
